### ISSUE TITLE
Fatal error in PDFEmbed, using userHasRight in PDFEmbed.hooks.php

### ISSUE THREAD

**Issue by bertrandgorge** [WolfgangFahl/PDFEmbed#14]
Hello, I get this fatal error when rebuilding data on SMW, with MW 1.35:

```
TypeError: Argument 1 passed to MediaWiki\Permissions\PermissionManager::userHasRight() must implement interface MediaWiki\User\UserIdentity, null given, called in /var/www/html/extensions/PDFEmbed/PDFEmbed.hooks.php on line 123
Backtrace:
from /var/www/html/includes/Permissions/PermissionManager.php(1366)
#0 /var/www/html/extensions/PDFEmbed/PDFEmbed.hooks.php(123): MediaWiki\Permissions\PermissionManager->userHasRight(NULL, string)
#1 /var/www/html/includes/parser/Parser.php(3973): PDFEmbed::generateTag(string, array, Parser, PPFrame_Hash)
#2 /var/www/html/includes/parser/PPFrame_Hash.php(350): Parser->extensionSubstitution(array, PPFrame_Hash)
#3 /var/www/html/includes/parser/Parser.php(2930): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#4 /var/www/html/includes/parser/Parser.php(1598): Parser->replaceVariables(string)
#5 /var/www/html/includes/parser/Parser.php(656): Parser->internalParse(string)
#6 /var/www/html/includes/content/WikitextContent.php(327): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#7 /var/www/html/includes/content/AbstractContent.php(548): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#8 /var/www/html/extensions/SemanticMediaWiki/includes/ContentParser.php(173): AbstractContent->getParserOutput(Title, integer)
#9 /var/www/html/extensions/SemanticMediaWiki/includes/ContentParser.php(130): SMW\ContentParser->fetchFromContent()
#10 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(197): SMW\ContentParser->parse()
#11 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#12 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#13 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#14 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(466): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(integer)
#15 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(integer)
#16 /var/www/html/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#17 /var/www/html/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#18 /var/www/html/maintenance/doMaintenance.php(108): SMW\Maintenance\rebuildData->execute()
#19 /var/www/html/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#20 {main}
```

**Comment by bertrandgorge** [comment]
Thanks for the merge !
